### ISSUE TITLE
Editing a Rectangle with the mouse could lead to PolylineException

### ISSUE THREAD

**Issue by dsn27** [SOFAgh/CADability#22]
If the user is editing a rectangle with the mouse and would reach the point where the rectangle would have 0 height the follwing execption occurs.

This error should be handled gracefully and not stop the program from running.

![11-02-_2021_09-00-23](https://user-images.githubusercontent.com/45662116/107613726-2a1eb500-6c49-11eb-8122-6b8183bee346.gif)

```
CADability.GeoObject.PolylineException
  HResult=0x80131600
  Message=Attempt to get rectangle location on polyline that is no rectangle
  Source=CADability
  StackTrace:
   at CADability.GeoObject.Polyline.get_RectangleLocation() in C:\Development\Repos\SOFAgh\CADability\CADability\Polyline.cs:line 293
   at CADability.UserInterface.ShowPropertyPolyline.OnGetLocation(GeoPointProperty sender) in C:\Development\Repos\SOFAgh\CADability\CADability\ShowPropertyPolyline.cs:line 367
   at CADability.UserInterface.GeoPointProperty.<>c__DisplayClass56_0.<add_GetGeoPointEvent>b__0() in C:\Development\Repos\SOFAgh\CADability\CADability\GeoPointProperty.cs:line 448
   at CADability.UserInterface.EditableProperty`1.GetValue() in C:\Development\Repos\SOFAgh\CADability\CADability\EditableProperty.cs:line 198
   at CADability.UserInterface.GeoPointProperty.CADability.IHotSpot.GetHotspotPosition() in C:\Development\Repos\SOFAgh\CADability\CADability\GeoPointProperty.cs:line 512
   at CADability.Actions.SelectObjectsAction.OnRepaintSelect(Rectangle IsInvalid, IView View, IPaintTo3D PaintToSelect) in C:\Development\Repos\SOFAgh\CADability\CADability\SelectObjectsAction.cs:line 571
   at CADability.ModelView.CADability.IView.OnPaint(PaintEventArgs e) in C:\Development\Repos\SOFAgh\CADability\CADability\ModelView.cs:line 809
   at CADability.Forms.CadCanvas.OnPaint(PaintEventArgs e) in C:\Development\Repos\SOFAgh\CADability\CADability.Forms\CadCanvas.cs:line 205
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by SOFAgh** [comment]
fixed
