### ISSUE TITLE
CADability.GeoVectorException

### ISSUE THREAD

**Issue by dsn27** [SOFAgh/CADability#57]
A GeoVectorException will occure if you select the upper right hole in the drawing and close the application.

![DB0CEA9D-BDB3-401D-A69A-7154A05A475E](https://user-images.githubusercontent.com/45662116/146515492-c62cd899-cb1a-4a09-be36-6ead2ba5908d.GIF)

[drawing1.zip](https://github.com/SOFAgh/CADability/files/7733693/drawing1.zip)
```
CADability.GeoVectorException
  HResult=0x80131600
  Message=Fehler in der Anwendung.
  Source=CADability
  StackTrace:
   at CADability.GeoVector2D.get_Normalized() in C:\Development\Repos\SOFAgh\CADability\CADability\GeoPoint.cs:line 1451
   at CADability.Curve2D.GeneralCurve2D.MakeTringulation() in C:\Development\Repos\SOFAgh\CADability\CADability\GeneralCurve2D.cs:line 1631
   at CADability.Curve2D.GeneralCurve2D.GetExtent() in C:\Development\Repos\SOFAgh\CADability\CADability\GeneralCurve2D.cs:line 3280
   at CADability.Curve2D.BSpline2D.GetExtent() in C:\Development\Repos\SOFAgh\CADability\CADability\BSpline2D.cs:line 3009
   at CADability.GeoObject.BSpline.GetExtent(Projection projection, ExtentPrecision extentPrecision) in C:\Development\Repos\SOFAgh\CADability\CADability\BSpline.cs:line 3971
   at CADability.Actions.SelectObjectsAction.GetDisplayExtent(Projection projection, IGeoObject geoObject) in C:\Development\Repos\SOFAgh\CADability\CADability\SelectObjectsAction.cs:line 386
   at CADability.Actions.SelectObjectsAction.GetDisplayExtent(Projection projection, GeoObjectList list) in C:\Development\Repos\SOFAgh\CADability\CADability\SelectObjectsAction.cs:line 393
   at CADability.Actions.SelectObjectsAction.RecalcFrameSize(IView vw, Int32& frameLeft, Int32& frameRight, Int32& frameBottom, Int32& frameTop) in C:\Development\Repos\SOFAgh\CADability\CADability\SelectObjectsAction.cs:line 407
   at CADability.Actions.SelectObjectsAction.GetFrameInvalidateRect(IView vw) in C:\Development\Repos\SOFAgh\CADability\CADability\SelectObjectsAction.cs:line 441
   at CADability.Actions.SelectObjectsAction.SetSelectedObjects(GeoObjectList selObj) in C:\Development\Repos\SOFAgh\CADability\CADability\SelectObjectsAction.cs:line 814
   at CADability.Actions.SelectObjectsAction.ClearSelectedObjects() in C:\Development\Repos\SOFAgh\CADability\CADability\SelectObjectsAction.cs:line 859
   at CADability.Actions.SelectObjectsAction.OnInactivate(Action NewActiveAction, Boolean RemovingAction) in C:\Development\Repos\SOFAgh\CADability\CADability\SelectObjectsAction.cs:line 946
   at CADability.ActionStack.RemoveActiveAction() in C:\Development\Repos\SOFAgh\CADability\CADability\ActionStack.cs:line 160
   at CADability.FrameImpl.RemoveActiveAction() in C:\Development\Repos\SOFAgh\CADability\CADability\Frame.cs:line 823
   at CADability.FrameImpl.Dispose() in C:\Development\Repos\SOFAgh\CADability\CADability\Frame.cs:line 797
   at CADability.Forms.CadControl.ParentForm_FormClosed(Object sender, FormClosedEventArgs e) in C:\Development\Repos\SOFAgh\CADability\CADability.Forms\CadControl.cs:line 193
   at System.Windows.Forms.Form.OnFormClosed(FormClosedEventArgs e)
   at System.Windows.Forms.Form.WmClose(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by SOFAgh** [comment]
fixed
